### ISSUE TITLE
Problems with api:set

### ISSUE THREAD

**Issue by j-fischer** [muenzpraeger/sfdx-plugin#6]
Hi,

I am trying to upgrade the API version in a DX project to the latest version, and keep getting following error:

`sfdx muenzpraeger:source:api:set
Reading content of package directories.
 !    Error: ENOENT: no such file or directory, scandir
 !    'C:\Path_To_Project\.sfdx\sfdx-config.json\force-app'`

Only when I specify the version directly, I am seeing another error:
`sfdx muenzpraeger:source:api:set -a 43.0
ERROR running SourceApiSet:  Cannot read property 'validateApiVersion' of undefined`

All commands were executed in the windows command line inside the project root folder. 

Any idea what I am missing here? Any help would be greatly appreciated.

Thanks!

**Comment by muenzpraeger** [comment]
Those are weird error messages, especially b/c validateApiVersion belongs to SfdxUtil from the @salesforce/core package.

Can you please run "sfdx update" and "sfdx plugins:update" to make sure that you're on the latest version, and then try again.

(Note: the latest version of my plugin now uses "mzpr" instead of "muenzpraeger" for the first topic)

**Comment by j-fischer** [comment]
I ran the update comments and still had the same issue. 

But you mentioned the namespace change, which lead me to use the install command from your readme, and that installed the new version of the plugin. 

With the mzpr topic, everything worked like a charm 👍 

I installed the plugin pretty soon after you released the first version and missed the update when the namespace was changed, hence never noticed that I wasn't on the latest version. 

Thanks for the super fast response! 
Cheers
